---
title: "VectorByte Training Materials 2024"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

# Overview

## Pre-work and set-up

### Hardware and Software

We will be using [`R`](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have `R` (version 3.6 or higher) installed.

You may use any IDE/ GUI for `R` (VScode, RStudio, Emacs, etc). For most people, [`RStudio`](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and test it before the workshop. We will have a channel on Slack dedicated to software/hardware issues and troubleshooting.

We will also be using Slack for additional support during the training. Please have these installed in advance.

### Pre-requisites


We are assuming familiarity with R basics as well as at least introductory statistics, including up through linear models. If you would like materials to review, we recommend that you do the following:

1.  Go to [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html), and read+work through the [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html).

2.  In addition / alternatively to pre-work element (1), here are some resources for brushing up on R [at the end of the Intro R Chapter you can try](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html#readings-and-resources). There are many more resources online (e.g., [this](https://www.codecademy.com/learn/learn-r) and [this](https://www.dataquest.io/blog/learn-r-for-data-science/) ) -- pick something that suits your learning style.

3.  Review background on [introductory probability and statistics](Stats_review.qmd) ([solutions to exercises](Stats_review_soln.qmd)). You can also use the resources on [The Multilingual Quantitative Biologist - Basic Data Analyses and Statistics](https://mhasoba.github.io/TheMulQuaBio/Stats-Intro.html) through into linear models. 

<br> <br>

## Introduction to Time Dependent Abundance Data


<br> <br>

## Introduction to the VecDyn database[^1]

[^1]: What is the difference between VectorBiTE and VectorByte? We are glad you asked! [VectorBiTE](http://vectorbite.org/) was an RCN or a research coordination network funded by a 5 year grant from the BBSRC. [VectorByte](https://www.vectorbyte.org/) is hosting this training which is a newly funded NSF grant to establish a global open access data platform to study disease vectors. All the databases have transitioned to VectorByte but the legacy options will still be available on the VectorBiTE website.

-   This component will be delivered live & synchronously. The VecDyn website can be found [here](https://vectorbyte.crc.nd.edu/vecdyn-datasets). It might be an idea to explore this prior to the workshop.

<br> <br>

## Regression Refresher

<br> <br>



## Time dependent regression analysis 

<br> <br>


## Basics of Time Series using R

<br> <br>


## Gaussian Process models (GPs) for Time Dependent Data

<br> <br>
