---
title: "2024 Training Schedule"
description: "Draft schedule for synchronous training sessions"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

[Main materials](materials.qmd)

# Pre-workshop

Information about pre-workshop preparation -- including software installation, expectations for what you should already be familiar with, and review materials -- is available in the [pre-work portion of the materials page](materials.html#pre-work-and-set-up).

<br> <br> <br>

# 22 July 2024

| Time | Activity | Materials |
|------|----------|-----------|
|      | Arrival  |           |

<br> <br> <br>

# 23 July 2024 (08:30 - 17:30)

| Time   | Activity | Materials |
|--------|----------|-----------|
| 8:30   | Introduction to time dependent data, course overview            |           |
| 9:30   | Goal setting, lighting presentations                                  |           |
| 10:15  | Break    |           |
| 10:45  | Lecture: Regression Transformations and Diagnostics         |           |
| 11:45  | Practical: Regression Transformations and Diagnostics         |           |
| 12:30  | Lunch    |           |
| 13:30  | Lecture: Time Dependent Data Analysis                                 |           |
| 14:30  | Practical: Time Dependent Data Analysis                               |           |
| 15:15  | Break    |           |
| 15:30  | Integrated Lecture and Practical: Basics of Time Series method       |           |


<br> <br> <br>

# 24 July 2024 (08:30 - 17:30)

| Time   | Activity | Materials |
|--------|----------|-----------|
| 8:30   | Overview  of the day         |           |
| 9:00   | Introduction to VecDyn Database and API                                   |           |
| 10:00  | Break    |           |
| 10:30  | Working with VecDyn/time dependent data (data aggregation, covariate/predictor sources)                                        |           |
| 12:30  | Lunch    |           |
| 13:30  | Lecture: Introduction to Gaussian Process (GP) regression applied to time dependent data                                        |           |
| 14:45  | Break    |           |
| 15:15  | Practical: GPs in R with `laGP` and `hetGP`                           |           |
| 16:30  | Brainstorming planning for projects                                   |           |
| 17:00  | Lightning talks                                                       |           |

<br>
<br>
<br>

# 25 July 2024 (08:30 - 17:30)

| Time.  | Activity                       | Materials |
|--------|--------------------------------|-----------|
| 8:30   | Overview  of the day           |           |
| 9:00   | Forecasting metrics and challenge introduction                                              |           |
| 9:30   | Forecasting Challenge          |           |
| 10:30  | Break                          |           |
| 11:00  | Forecasting Challenge (cont)   |           |
| 11:45  | Present and Eval forecasts     |           |
| 12:30  | Lunch                          |           |
| 13:30  | Mini projects                  |           |
| 15:00  | Break                          |           |
| 15:30  | Mini projects                  |           |
| 16:30  | Present mini projects; wrap up |           |



<br>
<br>
<br>

# 26 July 2024

| Time | Activity | Materials |
|------|----------|-----------|
|      | Travel   |           |

# Post-workshop

Enjoy using these new techniques and databases!

<br> <br> <br>
